# Generated by Django 5.1.3 on 2025-01-27 09:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='about',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
