# Generated by Django 5.1.3 on 2025-01-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_programs_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
