# Generated by Django 5.1.3 on 2025-01-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academics_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='excerpt',
            field=models.TextField(default='ABC'),
        ),
        migrations.AddField(
            model_name='programs',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
