# Generated by Django 5.1.3 on 2025-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_programs_excerpt_programs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
