# Generated by Django 5.1.3 on 2025-01-30 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_programs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='course',
        ),
        migrations.RemoveField(
            model_name='register',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='query',
        ),
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='register',
            name='grade',
            field=models.CharField(choices=[('kindergarten', 'kindergarten'), ('nursery', 'nursery'), ('1 class', '1 class'), ('2 class', '2 class'), ('3 class', '3 class'), ('4 class', '4 class'), ('5 class', '5 class'), ('6 class', '6 class'), ('7 class', '7 class'), ('8 class', '8 class'), ('9 class', '9 class'), ('10 class', '10 class')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='register',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
