# Generated by Django 5.1.3 on 2025-01-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_register_course_remove_register_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
