# Generated by Django 5.1.3 on 2025-01-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_subject_contact_address_remove_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
