# Generated by Django 5.1.3 on 2025-02-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_name_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academics',
            name='qualification',
        ),
        migrations.AddField(
            model_name='academics',
            name='forewords',
            field=models.TextField(default=''),
        ),
    ]
